#ifndef INCLUDEHEADER_H
#define INCLUDEHEADER_H

#include <QPainter>
#include <QPen>
#include <QBrush>
#include <QPaintEvent>
#include <QPixmap>
#include <QComboBox>
#include <QFont>
#include <QCheckBox>
#include <QWidget>
#include <QLabel>
#include <QColor>
#include <QString>
#include <QVector>
#include <QDebug>
#include <QFrame>
#include <QResizeEvent>
#include <QBitmap>
#include <QHoverEvent>
#include <QMoveEvent>
#include <QMouseEvent>
#include <QEnterEvent>
#include <QEvent>
#include <QStackedWidget>
#include <QPushButton>
#include <QLineEdit>
#include <QDateEdit>
#include <QMap>
#include <QMapIterator>
#include <QListView>
#include <QSqlDatabase>
#include <QSqlError>
#include <QSqlQuery>
#include <QSqlRecord>
#include <QDir>
#include <QLockFile>
#include <QMessageBox>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QThread>
#include <QEvent>
#include <QApplication>
#include <QMouseEvent>
#include <QDesktopWidget>
#include <QTimer>
#include <QVariant>
#include <QPushButton>

#endif // INCLUDEHEADER_H
